import { useState } from "react";
import {
  Cpu,
  Trash2,
  ToggleLeft,
  Thermometer,
  SlidersHorizontal,
  Palette,
  Type,
  Copy,
  Check,
} from "lucide-react";

interface CapabilityDef {
  id: string;
  type: "switch" | "sensor" | "slider" | "color" | "text";
  label: string;
  gpio: string;
  unit: string;
  min: string;
  max: string;
}

const CAP_ICONS = {
  switch: ToggleLeft,
  sensor: Thermometer,
  slider: SlidersHorizontal,
  color: Palette,
  text: Type,
};

const CAP_DEFAULTS: Record<string, Partial<CapabilityDef>> = {
  switch: { gpio: "2", unit: "", min: "", max: "" },
  sensor: { gpio: "", unit: "C", min: "", max: "" },
  slider: { gpio: "25", unit: "", min: "0", max: "100" },
  color: { gpio: "", unit: "", min: "", max: "" },
  text: { gpio: "", unit: "", min: "", max: "" },
};

export default function FirmwareGenerator() {
  const [deviceName, setDeviceName] = useState("My Device");
  const [board, setBoard] = useState<"esp32" | "picow">("esp32");
  const [capabilities, setCapabilities] = useState<CapabilityDef[]>([]);
  const [copied, setCopied] = useState(false);

  const addCapability = (type: CapabilityDef["type"]) => {
    const count = capabilities.filter((c) => c.type === type).length;
    const defaults = CAP_DEFAULTS[type];
    setCapabilities([
      ...capabilities,
      {
        id: `${type}_${count}`,
        type,
        label: `${type.charAt(0).toUpperCase() + type.slice(1)} ${count + 1}`,
        gpio: defaults.gpio || "",
        unit: defaults.unit || "",
        min: defaults.min || "",
        max: defaults.max || "",
      },
    ]);
  };

  const updateCapability = (index: number, field: string, value: string) => {
    setCapabilities(
      capabilities.map((c, i) =>
        i === index ? { ...c, [field]: value } : c,
      ),
    );
  };

  const removeCapability = (index: number) => {
    setCapabilities(capabilities.filter((_, i) => i !== index));
  };

  const generateSketch = (): string => {
    const lines: string[] = [];
    lines.push("/*");
    lines.push(` * ${deviceName} — Generated by Trellis`);
    lines.push(` * https://github.com/ovexro/trellis`);
    lines.push(" */");
    lines.push("");
    lines.push("#include <Trellis.h>");
    lines.push("");
    lines.push('const char* WIFI_SSID = "YourWiFi";');
    lines.push('const char* WIFI_PASS = "YourPassword";');
    lines.push("");
    lines.push(`Trellis trellis("${deviceName}");`);
    lines.push("");

    // Sensor read functions
    const sensors = capabilities.filter((c) => c.type === "sensor");
    for (const sensor of sensors) {
      lines.push(`float read_${sensor.id}() {`);
      if (sensor.gpio) {
        lines.push(`  int raw = analogRead(${sensor.gpio});`);
        lines.push("  // TODO: convert raw ADC to actual value");
        lines.push("  return raw * (3.3 / 4095.0) * 100.0;");
      } else {
        lines.push("  // TODO: read your sensor here");
        lines.push("  return 0.0;");
      }
      lines.push("}");
      lines.push("");
    }

    // Custom command handler if there are controllable capabilities
    const controllable = capabilities.filter(
      (c) => c.type === "switch" || c.type === "slider" || c.type === "color",
    );
    if (controllable.length > 0) {
      lines.push("void onCommand(const char* id, JsonVariant value) {");
      lines.push('  Serial.printf("Command: %s\\n", id);');
      lines.push("  // Add custom logic here");
      lines.push("}");
      lines.push("");
    }

    // Setup
    lines.push("void setup() {");
    lines.push('  trellis.setFirmwareVersion("1.0.0");');
    lines.push("");
    for (const cap of capabilities) {
      switch (cap.type) {
        case "switch":
          lines.push(
            `  trellis.addSwitch("${cap.id}", "${cap.label}", ${cap.gpio || "2"});`,
          );
          break;
        case "sensor":
          lines.push(
            `  trellis.addSensor("${cap.id}", "${cap.label}", "${cap.unit}");`,
          );
          break;
        case "slider":
          lines.push(
            `  trellis.addSlider("${cap.id}", "${cap.label}", ${cap.min}, ${cap.max}, ${cap.gpio || "25"});`,
          );
          break;
        case "color":
          lines.push(`  trellis.addColor("${cap.id}", "${cap.label}");`);
          break;
        case "text":
          lines.push(`  trellis.addText("${cap.id}", "${cap.label}");`);
          break;
      }
    }
    if (controllable.length > 0) {
      lines.push("");
      lines.push("  trellis.onCommand(onCommand);");
    }
    lines.push("  trellis.begin(WIFI_SSID, WIFI_PASS);");
    lines.push("}");
    lines.push("");

    // Loop
    lines.push("void loop() {");
    if (sensors.length > 0) {
      lines.push("  // Update sensor readings");
      for (const sensor of sensors) {
        lines.push(
          `  trellis.setSensor("${sensor.id}", read_${sensor.id}());`,
        );
      }
      lines.push("");
    }
    lines.push("  trellis.loop();");
    if (sensors.length > 0) {
      lines.push("  delay(2000); // Read sensors every 2 seconds");
    }
    lines.push("}");

    return lines.join("\n");
  };

  const sketch = generateSketch();

  const copySketch = () => {
    navigator.clipboard.writeText(sketch);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex gap-6 h-full">
      {/* Left: Configuration */}
      <div className="w-80 flex-shrink-0 overflow-auto">
        <h1 className="text-xl font-bold text-zinc-100 mb-1">
          New Device
        </h1>
        <p className="text-sm text-zinc-500 mb-6">
          Pick capabilities and get a ready-to-flash Arduino sketch.
        </p>

        <div className="space-y-4">
          <div>
            <label className="block text-xs text-zinc-400 mb-1">
              Device Name
            </label>
            <input
              type="text"
              value={deviceName}
              onChange={(e) => setDeviceName(e.target.value)}
              className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-zinc-300"
            />
          </div>

          <div>
            <label className="block text-xs text-zinc-400 mb-1">Board</label>
            <select
              value={board}
              onChange={(e) => setBoard(e.target.value as "esp32" | "picow")}
              className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-zinc-300"
            >
              <option value="esp32">ESP32</option>
              <option value="picow">Raspberry Pi Pico W</option>
            </select>
          </div>

          <div>
            <label className="block text-xs text-zinc-400 mb-2">
              Add Capabilities
            </label>
            <div className="flex flex-wrap gap-1.5">
              {(
                Object.keys(CAP_ICONS) as Array<keyof typeof CAP_ICONS>
              ).map((type) => {
                const Icon = CAP_ICONS[type];
                return (
                  <button
                    key={type}
                    onClick={() => addCapability(type)}
                    className="flex items-center gap-1.5 px-2.5 py-1.5 bg-zinc-800 hover:bg-zinc-700 border border-zinc-700 rounded-lg text-xs text-zinc-300 transition-colors"
                  >
                    <Icon size={12} />
                    {type}
                  </button>
                );
              })}
            </div>
          </div>

          {capabilities.length > 0 && (
            <div className="space-y-2">
              <label className="block text-xs text-zinc-400">
                Capabilities ({capabilities.length})
              </label>
              {capabilities.map((cap, i) => {
                const Icon = CAP_ICONS[cap.type];
                return (
                  <div
                    key={i}
                    className="p-3 bg-zinc-800/50 border border-zinc-700/50 rounded-lg"
                  >
                    <div className="flex items-center justify-between mb-2">
                      <span className="flex items-center gap-1.5 text-xs text-zinc-400">
                        <Icon size={12} />
                        {cap.type}
                      </span>
                      <button
                        onClick={() => removeCapability(i)}
                        className="p-0.5 text-zinc-600 hover:text-red-400 transition-colors"
                      >
                        <Trash2 size={12} />
                      </button>
                    </div>
                    <div className="space-y-1.5">
                      <input
                        type="text"
                        value={cap.label}
                        onChange={(e) =>
                          updateCapability(i, "label", e.target.value)
                        }
                        placeholder="Label"
                        className="w-full bg-zinc-900 border border-zinc-700 rounded px-2 py-1 text-xs text-zinc-300"
                      />
                      <div className="flex gap-1.5">
                        {(cap.type === "switch" || cap.type === "slider") && (
                          <input
                            type="text"
                            value={cap.gpio}
                            onChange={(e) =>
                              updateCapability(i, "gpio", e.target.value)
                            }
                            placeholder="GPIO"
                            className="w-16 bg-zinc-900 border border-zinc-700 rounded px-2 py-1 text-xs text-zinc-300"
                          />
                        )}
                        {cap.type === "sensor" && (
                          <input
                            type="text"
                            value={cap.unit}
                            onChange={(e) =>
                              updateCapability(i, "unit", e.target.value)
                            }
                            placeholder="Unit"
                            className="w-16 bg-zinc-900 border border-zinc-700 rounded px-2 py-1 text-xs text-zinc-300"
                          />
                        )}
                        {cap.type === "slider" && (
                          <>
                            <input
                              type="text"
                              value={cap.min}
                              onChange={(e) =>
                                updateCapability(i, "min", e.target.value)
                              }
                              placeholder="Min"
                              className="w-14 bg-zinc-900 border border-zinc-700 rounded px-2 py-1 text-xs text-zinc-300"
                            />
                            <input
                              type="text"
                              value={cap.max}
                              onChange={(e) =>
                                updateCapability(i, "max", e.target.value)
                              }
                              placeholder="Max"
                              className="w-14 bg-zinc-900 border border-zinc-700 rounded px-2 py-1 text-xs text-zinc-300"
                            />
                          </>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* Right: Generated code */}
      <div className="flex-1 flex flex-col min-w-0">
        <div className="flex items-center justify-between mb-2">
          <h2 className="text-sm font-semibold text-zinc-400 flex items-center gap-2">
            <Cpu size={14} />
            Generated Sketch
          </h2>
          <button
            onClick={copySketch}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-trellis-500 hover:bg-trellis-600 text-white rounded-lg text-xs font-medium transition-colors"
          >
            {copied ? <Check size={12} /> : <Copy size={12} />}
            {copied ? "Copied!" : "Copy to clipboard"}
          </button>
        </div>
        <pre className="flex-1 bg-zinc-950 border border-zinc-800 rounded-lg p-4 overflow-auto text-xs text-zinc-300 font-mono leading-5 select-text">
          {sketch}
        </pre>
      </div>
    </div>
  );
}
