/**
 * Arduino sketch generator — shared between FirmwareGenerator and GetStarted wizard.
 */

export interface SketchCapability {
  id: string;
  type: "switch" | "sensor" | "slider" | "color" | "text";
  label: string;
  gpio: string;
  unit: string;
  min: string;
  max: string;
}

function escCpp(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function generateSketch(
  deviceName: string,
  board: "esp32" | "picow",
  capabilities: SketchCapability[],
): string {
  const lines: string[] = [];
  lines.push("/*");
  lines.push(` * ${escCpp(deviceName)} — Generated by Trellis`);
  lines.push(` * Board: ${board === "esp32" ? "ESP32" : "Raspberry Pi Pico W"}`);
  lines.push(` * https://github.com/ovexro/trellis`);
  lines.push(` *`);
  lines.push(` * First boot: device creates a WiFi hotspot "Trellis-${escCpp(deviceName).replace(/ /g, "-")}".`);
  lines.push(` * Connect to it and enter your WiFi credentials. They are saved for next boot.`);
  lines.push(" */");
  lines.push("");
  lines.push("#include <Trellis.h>");
  lines.push("");
  lines.push(`Trellis trellis("${escCpp(deviceName)}");`);
  lines.push("");

  // Sensor read functions
  const sensors = capabilities.filter((c) => c.type === "sensor");
  for (const sensor of sensors) {
    lines.push(`float read_${sensor.id}() {`);
    if (sensor.gpio) {
      lines.push(`  int raw = analogRead(${sensor.gpio});`);
      lines.push("  // TODO: convert raw ADC to actual value");
      lines.push("  return raw * (3.3 / 4095.0) * 100.0;");
    } else {
      lines.push("  // TODO: read your sensor here");
      lines.push("  return 0.0;");
    }
    lines.push("}");
    lines.push("");
  }

  // Custom command handler if there are controllable capabilities
  const controllable = capabilities.filter(
    (c) => c.type === "switch" || c.type === "slider" || c.type === "color",
  );
  if (controllable.length > 0) {
    lines.push("void onCommand(const char* id, JsonVariant value) {");
    lines.push('  Serial.printf("Command: %s\\n", id);');
    lines.push("  // Add custom logic here");
    lines.push("}");
    lines.push("");
  }

  // Setup
  lines.push("void setup() {");
  lines.push('  trellis.setFirmwareVersion("1.0.0");');
  lines.push("");
  for (const cap of capabilities) {
    switch (cap.type) {
      case "switch":
        lines.push(
          `  trellis.addSwitch("${escCpp(cap.id)}", "${escCpp(cap.label)}", ${cap.gpio || "2"});`,
        );
        break;
      case "sensor":
        lines.push(
          `  trellis.addSensor("${escCpp(cap.id)}", "${escCpp(cap.label)}", "${escCpp(cap.unit)}");`,
        );
        break;
      case "slider":
        lines.push(
          `  trellis.addSlider("${escCpp(cap.id)}", "${escCpp(cap.label)}", ${cap.min}, ${cap.max}, ${cap.gpio || "25"});`,
        );
        break;
      case "color":
        lines.push(`  trellis.addColor("${escCpp(cap.id)}", "${escCpp(cap.label)}");`);
        break;
      case "text":
        lines.push(`  trellis.addText("${escCpp(cap.id)}", "${escCpp(cap.label)}");`);
        break;
    }
  }
  if (controllable.length > 0) {
    lines.push("");
    lines.push("  trellis.onCommand(onCommand);");
  }
  lines.push("");
  lines.push("  // WiFi: uses stored credentials or starts provisioning AP");
  lines.push("  if (!trellis.beginAutoConnect()) {");
  lines.push('    Serial.println("WiFi failed! Restarting...");');
  lines.push("    delay(3000);");
  if (board === "esp32") {
    lines.push("    ESP.restart();");
  } else {
    lines.push("    rp2040.reboot();");
  }
  lines.push("  }");
  lines.push("}");
  lines.push("");

  // Loop
  lines.push("void loop() {");
  if (sensors.length > 0) {
    lines.push("  // Update sensor readings");
    for (const sensor of sensors) {
      lines.push(
        `  trellis.setSensor("${escCpp(sensor.id)}", read_${sensor.id}());`,
      );
    }
    lines.push("");
  }
  lines.push("  trellis.loop();");
  if (sensors.length > 0) {
    lines.push("  delay(2000); // Read sensors every 2 seconds");
  }
  lines.push("}");

  return lines.join("\n");
}
