#!/usr/bin/env python3
"""Regenerate src/TrellisWebUI_html.h from src/web_ui.html.

The Arduino library embeds the on-device web dashboard as a PROGMEM byte
array so it streams directly from flash without consuming RAM. After
editing src/web_ui.html, run this script to refresh the generated header.

  python3 scripts/build_web_ui_header.py

Also emits a 16-char SHA-256 prefix as TRELLIS_WEB_UI_HTML_HASH so the
HTTP server can use it as an ETag. Tying the ETag to a content hash
(rather than only TRELLIS_VERSION) means the browser cache invalidates
whenever the HTML actually changes, even on patch releases that forget
to bump the version macro.
"""
import hashlib
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC = os.path.join(ROOT, "src", "web_ui.html")
DST = os.path.join(ROOT, "src", "TrellisWebUI_html.h")
DELIM = "TWUI"

def main():
    with open(SRC, "rb") as f:
        data = f.read().strip(b"\r\n ")
    if DELIM.encode() in data:
        sys.exit(f"error: delimiter {DELIM!r} appears inside the HTML; pick another")
    text = data.decode("utf-8")
    # 16 hex chars = 64 bits — collision-negligible for ETag purposes,
    # short enough that the HTTP header stays compact.
    content_hash = hashlib.sha256(data).hexdigest()[:16]
    out = (
        "// Auto-generated from src/web_ui.html by scripts/build_web_ui_header.py\n"
        "// Do not edit this file by hand — edit web_ui.html and regenerate.\n"
        "#ifndef TRELLIS_WEB_UI_HTML_H\n"
        "#define TRELLIS_WEB_UI_HTML_H\n"
        "#include <Arduino.h>\n\n"
        f'static const char TRELLIS_WEB_UI_HTML[] PROGMEM = R"{DELIM}({text}){DELIM}";\n'
        f'static const char TRELLIS_WEB_UI_HTML_HASH[] = "{content_hash}";\n\n'
        "#endif\n"
    )
    with open(DST, "w") as f:
        f.write(out)
    print(f"wrote {DST} ({len(data)} bytes of HTML, hash {content_hash})")

if __name__ == "__main__":
    main()
