// Auto-generated from src/web_ui.html by scripts/build_web_ui_header.py
// Do not edit this file by hand — edit web_ui.html and regenerate.
#ifndef TRELLIS_WEB_UI_HTML_H
#define TRELLIS_WEB_UI_HTML_H
#include <Arduino.h>

static const char TRELLIS_WEB_UI_HTML[] PROGMEM = R"TWUI(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="dark">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="mobile-web-app-capable" content="yes">
<meta name="theme-color" content="#0b0d10">
<title>Trellis</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%235eead4'/%3E%3Ctext x='16' y='22' font-family='system-ui,sans-serif' font-size='20' font-weight='800' text-anchor='middle' fill='%23062c2e'%3ET%3C/text%3E%3C/svg%3E">
<link rel="apple-touch-icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 180 180'%3E%3Crect width='180' height='180' rx='40' fill='%235eead4'/%3E%3Ctext x='90' y='124' font-family='system-ui,sans-serif' font-size='112' font-weight='800' text-anchor='middle' fill='%23062c2e'%3ET%3C/text%3E%3C/svg%3E">
<style>
:root{
  --bg:#0b0d10;--panel:#15181d;--panel2:#1c2026;--bd:#252a32;
  --fg:#e7ecf3;--mut:#8a93a3;--acc:#5eead4;--accd:#2dd4bf;
  --ok:#22c55e;--warn:#f59e0b;--err:#ef4444;--shadow:0 1px 0 #ffffff08 inset,0 8px 24px #00000040;
}
*{box-sizing:border-box}
html,body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.45 -apple-system,system-ui,Segoe UI,Roboto,sans-serif;-webkit-font-smoothing:antialiased;overflow-x:hidden}
a{color:var(--acc)}
.wrap{max-width:720px;margin:0 auto;padding:max(16px,env(safe-area-inset-top)) 16px max(24px,env(safe-area-inset-bottom))}
header{display:flex;align-items:center;gap:12px;margin:8px 0 18px;min-width:0}
header .logo{width:34px;height:34px;border-radius:9px;background:linear-gradient(135deg,var(--acc),#0ea5b1);display:grid;place-items:center;font-weight:800;color:#06292a;box-shadow:var(--shadow);flex:none}
header .ttl{flex:1;min-width:0;overflow:hidden}
header h1{font-size:18px;margin:0;font-weight:700;letter-spacing:.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
header .sub{font-size:12px;color:var(--mut);margin-top:1px;display:flex;gap:6px;align-items:center;flex-wrap:wrap}
.dot{width:8px;height:8px;border-radius:50%;background:var(--mut);box-shadow:0 0 0 3px #ffffff08}
.dot.on{background:var(--ok);box-shadow:0 0 0 3px #22c55e22}
.dot.off{background:var(--err);box-shadow:0 0 0 3px #ef444422}
.badge{font-size:10px;text-transform:uppercase;letter-spacing:.6px;color:var(--mut);border:1px solid var(--bd);padding:2px 6px;border-radius:999px}
.sys{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:18px}
.sys div{background:var(--panel);border:1px solid var(--bd);border-radius:12px;padding:10px 12px;box-shadow:var(--shadow)}
.sys b{display:block;font-size:11px;color:var(--mut);font-weight:500;text-transform:uppercase;letter-spacing:.5px;margin-bottom:3px}
.sys span{font-size:15px;font-weight:600;font-variant-numeric:tabular-nums}
.grid{display:grid;grid-template-columns:1fr;gap:12px}
@media(min-width:560px){.grid{grid-template-columns:1fr 1fr}.full{grid-column:1/-1}}
.card{background:var(--panel);border:1px solid var(--bd);border-radius:14px;padding:14px 16px;box-shadow:var(--shadow);transition:border-color .15s}
.card:hover{border-color:#2f3540}
.card h3{margin:0 0 4px;font-size:11px;text-transform:uppercase;letter-spacing:.6px;color:var(--mut);font-weight:600}
.row{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:6px}
.val{font-size:30px;font-weight:700;font-variant-numeric:tabular-nums;line-height:1.1}
.unit{font-size:14px;color:var(--mut);margin-left:4px;font-weight:500}
/* switch */
.sw{position:relative;width:54px;height:30px;flex:none}
.sw input{opacity:0;width:0;height:0}
.sw .slot{position:absolute;inset:0;background:#2a2f38;border-radius:999px;transition:.2s;cursor:pointer;border:1px solid var(--bd)}
.sw .slot:before{content:"";position:absolute;left:3px;top:3px;width:22px;height:22px;background:#cbd5e1;border-radius:50%;transition:.2s;box-shadow:0 1px 4px #0006}
.sw input:checked+.slot{background:var(--accd);border-color:var(--accd)}
.sw input:checked+.slot:before{transform:translateX(24px);background:#fff}
/* slider */
input[type=range]{-webkit-appearance:none;appearance:none;width:100%;height:6px;background:#2a2f38;border-radius:999px;outline:none;margin:10px 0 4px}
input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:20px;height:20px;border-radius:50%;background:var(--acc);cursor:pointer;box-shadow:0 0 0 4px #5eead422,0 2px 6px #0008;border:none}
input[type=range]::-moz-range-thumb{width:20px;height:20px;border-radius:50%;background:var(--acc);cursor:pointer;border:none;box-shadow:0 0 0 4px #5eead422}
/* color */
input[type=color]{-webkit-appearance:none;appearance:none;width:48px;height:48px;border:1px solid var(--bd);border-radius:12px;background:transparent;padding:0;cursor:pointer}
input[type=color]::-webkit-color-swatch-wrapper{padding:3px}
input[type=color]::-webkit-color-swatch{border:none;border-radius:9px}
input[type=color]::-moz-color-swatch{border:none;border-radius:9px}
.hex{font-family:ui-monospace,Menlo,monospace;font-size:13px;color:var(--mut);letter-spacing:.5px}
/* text */
.tx{display:flex;gap:8px;margin-top:8px}
.tx input{flex:1;background:var(--panel2);border:1px solid var(--bd);color:var(--fg);border-radius:10px;padding:9px 12px;font:inherit;outline:none;transition:border-color .15s}
.tx input:focus{border-color:var(--acc)}
.tx button{background:var(--accd);color:#06292a;border:none;border-radius:10px;padding:0 14px;font-weight:700;cursor:pointer;font:inherit;transition:filter .15s}
.tx button:hover{filter:brightness(1.1)}
.tx button:active{transform:translateY(1px)}
.tdisp{font-size:18px;font-weight:600;margin-top:6px;word-break:break-word}
.empty{color:var(--mut);text-align:center;padding:36px 16px;border:1px dashed var(--bd);border-radius:14px}
footer{margin-top:24px;text-align:center;color:var(--mut);font-size:11px}
footer a{text-decoration:none}
.toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%) translateY(60px);background:var(--panel2);border:1px solid var(--bd);color:var(--fg);padding:9px 16px;border-radius:999px;font-size:13px;box-shadow:0 8px 24px #000a;opacity:0;transition:.25s;pointer-events:none;z-index:50}
.toast.show{opacity:1;transform:translateX(-50%) translateY(0)}
/* header chips (logs toggle) */
.chip{display:inline-flex;align-items:center;gap:5px;background:var(--panel2);border:1px solid var(--bd);color:var(--fg);font:600 11px/1 -apple-system,system-ui,sans-serif;text-transform:uppercase;letter-spacing:.6px;padding:5px 9px;border-radius:999px;cursor:pointer;transition:border-color .15s,background .15s;flex:none}
.chip:hover{border-color:#3a4150;background:#1f242c}
.chip.active{border-color:var(--acc);background:#5eead412;color:var(--acc)}
.chip .ind{display:inline-block;width:5px;height:5px;border-radius:50%;background:var(--mut)}
.chip.active .ind{background:var(--acc)}
.chip .ct{background:var(--acc);color:#06292a;font-size:10px;font-weight:800;padding:1px 5px;border-radius:999px;min-width:14px;text-align:center;display:none}
.chip .ct.show{display:inline-block}
/* log panel */
.logp{margin-top:14px;background:var(--panel);border:1px solid var(--bd);border-radius:14px;box-shadow:var(--shadow);overflow:hidden;display:none}
.logp.open{display:block}
.logp .lh{display:flex;align-items:center;gap:8px;padding:10px 14px;border-bottom:1px solid var(--bd);background:var(--panel2)}
.logp .lh b{font-size:11px;text-transform:uppercase;letter-spacing:.6px;color:var(--mut);font-weight:600;flex:1}
.logp .lh button{background:transparent;border:1px solid var(--bd);color:var(--mut);font:600 10px/1 -apple-system,system-ui,sans-serif;text-transform:uppercase;letter-spacing:.5px;padding:5px 9px;border-radius:7px;cursor:pointer;transition:.15s}
.logp .lh button:hover{color:var(--fg);border-color:#3a4150}
.logp .lh button.on{color:var(--acc);border-color:var(--acc)}
.logp .lb{max-height:240px;overflow-y:auto;font:12px/1.55 ui-monospace,Menlo,Consolas,monospace;padding:8px 14px}
.logp .lb .ln{padding:2px 0;display:flex;gap:8px;border-top:1px solid #ffffff05;word-break:break-word}
.logp .lb .ln:first-child{border-top:none}
.logp .lb .t{color:var(--mut);flex:none;font-variant-numeric:tabular-nums}
.logp .lb .s{flex:none;font-weight:700;text-transform:uppercase;font-size:10px;padding:1px 5px;border-radius:4px;align-self:flex-start;margin-top:1px}
.logp .lb .s.info{background:#5eead418;color:var(--acc)}
.logp .lb .s.warn{background:#f59e0b1f;color:var(--warn)}
.logp .lb .s.error{background:#ef44441f;color:var(--err)}
.logp .lb .m{color:var(--fg);flex:1;min-width:0;white-space:pre-wrap}
.logp .lb .empty{color:var(--mut);text-align:center;padding:20px 8px;border:none}
/* OTA overlay */
.ota{position:fixed;inset:0;background:#000000c8;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px);display:none;align-items:center;justify-content:center;z-index:100;padding:20px;animation:fade .2s ease}
.ota.show{display:flex}
@keyframes fade{from{opacity:0}to{opacity:1}}
.ota .box{background:var(--panel);border:1px solid var(--bd);border-radius:16px;padding:24px;width:100%;max-width:340px;box-shadow:0 24px 60px #000c;text-align:center}
.ota .ic{width:48px;height:48px;border-radius:14px;background:linear-gradient(135deg,var(--acc),#0ea5b1);display:inline-grid;place-items:center;margin-bottom:14px;color:#06292a;font-size:24px}
.ota.fail .ic{background:linear-gradient(135deg,#ef4444,#b91c1c);color:#fff}
.ota h2{margin:0 0 4px;font-size:17px;font-weight:700}
.ota p{margin:0 0 16px;font-size:13px;color:var(--mut)}
.ota .bar{width:100%;height:8px;background:#2a2f38;border-radius:999px;overflow:hidden;margin-bottom:10px}
.ota .bar i{display:block;height:100%;width:0%;background:linear-gradient(90deg,var(--acc),var(--accd));transition:width .3s;border-radius:999px}
.ota.fail .bar i{background:var(--err);width:100%}
.ota .pct{font-size:11px;color:var(--mut);font-variant-numeric:tabular-nums;text-transform:uppercase;letter-spacing:.6px}
.ota .dis{margin-top:14px;background:transparent;border:1px solid var(--bd);color:var(--mut);padding:7px 14px;border-radius:8px;font:600 11px/1 -apple-system,system-ui,sans-serif;text-transform:uppercase;letter-spacing:.5px;cursor:pointer;display:none}
.ota.fail .dis{display:inline-block;color:var(--fg);border-color:#3a4150}
.ota.fail .dis:hover{border-color:var(--err);color:var(--err)}
/* PWA install hint (mobile only) */
.pwa{position:fixed;left:12px;right:12px;bottom:max(12px,env(safe-area-inset-bottom));background:var(--panel2);border:1px solid var(--bd);border-radius:14px;padding:14px 16px;box-shadow:0 12px 32px #000a;display:none;align-items:center;gap:12px;z-index:60;animation:rise .3s ease}
.pwa.show{display:flex}
@keyframes rise{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}
.pwa .pi{width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,var(--acc),#0ea5b1);display:grid;place-items:center;color:#06292a;font-weight:800;flex:none}
.pwa .pt{flex:1;min-width:0}
.pwa .pt b{display:block;font-size:13px;font-weight:600;margin-bottom:1px}
.pwa .pt span{font-size:11px;color:var(--mut)}
.pwa .px{background:transparent;border:none;color:var(--mut);font-size:20px;line-height:1;padding:4px 8px;cursor:pointer;border-radius:6px;flex:none}
.pwa .px:hover{color:var(--fg);background:#ffffff0a}
</style>
</head>
<body>
<div class="wrap">
  <header>
    <div class="logo">T</div>
    <div class="ttl">
      <h1 id="name">Trellis Device</h1>
      <div class="sub">
        <span class="dot" id="dot"></span>
        <span id="status">connecting…</span>
        <span class="badge" id="plat"></span>
        <span class="badge" id="fw"></span>
      </div>
    </div>
    <button class="chip" id="logToggle" type="button" aria-pressed="false" aria-label="Toggle log panel"><span class="ind"></span>Logs<span class="ct" id="logCt">0</span></button>
  </header>
  <div class="sys">
    <div><b>Signal</b><span id="rssi">—</span></div>
    <div><b>Free heap</b><span id="heap">—</span></div>
    <div><b>Uptime</b><span id="up">—</span></div>
  </div>
  <div class="grid" id="grid"></div>
  <section class="logp" id="logPanel" aria-label="Device logs">
    <div class="lh">
      <b>Live Logs</b>
      <button type="button" id="logPause">Pause</button>
      <button type="button" id="logClear">Clear</button>
    </div>
    <div class="lb" id="logBody"><div class="empty">Waiting for log events…</div></div>
  </section>
  <footer>Powered by <a href="https://github.com/ovexro/trellis" target="_blank" rel="noopener">Trellis</a> · <span id="id">—</span></footer>
</div>
<div class="toast" id="toast"></div>
<div class="ota" id="otaOverlay" role="dialog" aria-modal="true" aria-labelledby="otaTitle">
  <div class="box">
    <div class="ic" id="otaIc">↑</div>
    <h2 id="otaTitle">Updating firmware</h2>
    <p id="otaMsg">Please keep this page open. Device will reboot when done.</p>
    <div class="bar"><i id="otaBar"></i></div>
    <div class="pct" id="otaPct">starting…</div>
    <button type="button" class="dis" id="otaDismiss">Dismiss</button>
  </div>
</div>
<div class="pwa" id="pwaHint" role="dialog" aria-label="Install hint">
  <div class="pi">T</div>
  <div class="pt"><b id="pwaTitle">Add to Home Screen</b><span id="pwaSub">Install for one-tap access</span></div>
  <button type="button" class="px" id="pwaClose" aria-label="Dismiss">×</button>
</div>
<script>
(function(){
var host=location.hostname,wsPort=(parseInt(location.port||"80",10))+1,ws,reconnectT,caps={},info=null;
var $=function(s){return document.getElementById(s)};
function esc(s){return(""+s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function toast(t){var e=$("toast");e.textContent=t;e.classList.add("show");clearTimeout(toast._t);toast._t=setTimeout(function(){e.classList.remove("show")},1800)}
function setStatus(state,txt){var d=$("dot"),s=$("status");d.className="dot "+state;s.textContent=txt}
function fmtUp(s){if(s<60)return s+"s";var m=Math.floor(s/60);if(m<60)return m+"m";var h=Math.floor(m/60);if(h<48)return h+"h "+(m%60)+"m";return Math.floor(h/24)+"d "+(h%24)+"h"}
function fmtHeap(b){if(b>=1048576)return(b/1048576).toFixed(1)+" MB";if(b>=1024)return(b/1024).toFixed(0)+" KB";return b+" B"}
function fmtRssi(r){return r+" dBm"}
function send(id,value){if(!ws||ws.readyState!==1){toast("Not connected");return}ws.send(JSON.stringify({command:"set",id:id,value:value}))}
function renderSystem(s){if(!s)return;if(s.rssi!=null)$("rssi").textContent=fmtRssi(s.rssi);if(s.heap_free!=null)$("heap").textContent=fmtHeap(s.heap_free);if(s.uptime_s!=null)$("up").textContent=fmtUp(s.uptime_s)}
function buildCard(c){
  var card=document.createElement("div");card.className="card";
  if(c.type==="text")card.classList.add("full");
  var h=document.createElement("h3");h.textContent=c.label||c.id;card.appendChild(h);
  if(c.type==="switch"){
    var row=document.createElement("div");row.className="row";
    var v=document.createElement("div");v.className="val";v.id="v_"+c.id;v.textContent=c.value?"On":"Off";
    var sw=document.createElement("label");sw.className="sw";
    sw.innerHTML='<input type="checkbox" '+(c.value?"checked":"")+'><span class="slot"></span>';
    sw.querySelector("input").addEventListener("change",function(e){send(c.id,e.target.checked)});
    row.appendChild(v);row.appendChild(sw);card.appendChild(row);
  }else if(c.type==="slider"){
    var row2=document.createElement("div");row2.className="row";
    var unitSpan='<span class="unit">'+esc(c.min)+"–"+esc(c.max)+"</span>";
    var vv=document.createElement("div");vv.className="val";vv.id="v_"+c.id;vv.innerHTML=Math.round(c.value)+unitSpan;
    row2.appendChild(vv);card.appendChild(row2);
    var r=document.createElement("input");r.type="range";r.min=c.min;r.max=c.max;r.value=c.value;r.step=(c.max-c.min)>10?1:0.1;
    var commit;
    r.addEventListener("input",function(e){vv.innerHTML=Math.round(e.target.value)+unitSpan;clearTimeout(commit);commit=setTimeout(function(){send(c.id,parseFloat(e.target.value))},80)});
    card.appendChild(r);
  }else if(c.type==="sensor"){
    var row3=document.createElement("div");row3.className="row";
    var sv=document.createElement("div");sv.className="val";sv.id="v_"+c.id;
    var unitS=c.unit?'<span class="unit">'+esc(c.unit)+"</span>":"";
    sv.innerHTML=(typeof c.value==="number"?(Math.abs(c.value)<10?c.value.toFixed(2):c.value.toFixed(1)):"—")+unitS;
    sv.dataset.unit=unitS;
    row3.appendChild(sv);card.appendChild(row3);
  }else if(c.type==="color"){
    var row4=document.createElement("div");row4.className="row";
    var cp=document.createElement("input");cp.type="color";cp.value=c.value||"#000000";cp.id="v_"+c.id;
    var hx=document.createElement("div");hx.className="hex";hx.id="hx_"+c.id;hx.textContent=(c.value||"#000000").toUpperCase();
    var commit2;
    cp.addEventListener("input",function(e){hx.textContent=e.target.value.toUpperCase();clearTimeout(commit2);commit2=setTimeout(function(){send(c.id,e.target.value)},80)});
    row4.appendChild(hx);row4.appendChild(cp);card.appendChild(row4);
  }else if(c.type==="text"){
    var disp=document.createElement("div");disp.className="tdisp";disp.id="v_"+c.id;disp.textContent=c.value||"";
    card.appendChild(disp);
    var bx=document.createElement("div");bx.className="tx";
    var ti=document.createElement("input");ti.type="text";ti.placeholder="Enter text…";ti.maxLength=31;
    var bt=document.createElement("button");bt.textContent="Set";
    function go(){if(!ti.value)return;send(c.id,ti.value);ti.value=""}
    bt.addEventListener("click",go);
    ti.addEventListener("keydown",function(e){if(e.key==="Enter")go()});
    bx.appendChild(ti);bx.appendChild(bt);card.appendChild(bx);
  }
  return card;
}
function applyUpdate(id,value){
  var c=caps[id];if(!c)return;
  var el=$("v_"+id);if(!el)return;
  if(c.type==="switch"){el.textContent=value?"On":"Off";var i=el.parentNode.querySelector("input");if(i)i.checked=!!value}
  else if(c.type==="slider"){el.innerHTML=Math.round(value)+'<span class="unit">'+esc(c.min)+"–"+esc(c.max)+"</span>";var rr=el.parentNode.parentNode.querySelector('input[type=range]');if(rr&&document.activeElement!==rr)rr.value=value}
  else if(c.type==="sensor"){el.innerHTML=(typeof value==="number"?(Math.abs(value)<10?value.toFixed(2):value.toFixed(1)):esc(value))+(el.dataset.unit||"")}
  else if(c.type==="color"){if(document.activeElement!==el)el.value=value;var hh=$("hx_"+id);if(hh)hh.textContent=(""+value).toUpperCase()}
  else if(c.type==="text"){el.textContent=value}
}
function loadInfo(){
  fetch("/api/info").then(function(r){return r.json()}).then(function(d){
    info=d;
    $("name").textContent=d.name||"Trellis Device";document.title=(d.name||"Trellis")+" · Trellis";
    $("plat").textContent=d.platform||"";
    $("fw").textContent=d.firmware?"v"+d.firmware:"";
    $("id").textContent=d.id||"";
    renderSystem(d.system);
    var g=$("grid");g.innerHTML="";caps={};
    if(!d.capabilities||!d.capabilities.length){g.innerHTML='<div class="empty full">No capabilities exposed yet.</div>';}
    else{d.capabilities.forEach(function(c){caps[c.id]=c;g.appendChild(buildCard(c))});}
    connectWs();
  }).catch(function(){setStatus("off","unreachable");setTimeout(loadInfo,3000)});
}
function connectWs(){
  try{ws=new WebSocket("ws://"+host+":"+wsPort+"/")}catch(e){return scheduleReconnect()}
  ws.onopen=function(){setStatus("on","live");if(ota.shown&&!ota.failed){location.reload()}};
  ws.onclose=function(){setStatus("off","reconnecting…");if(ota.shown&&!ota.failed){otaReboot()}scheduleReconnect()};
  ws.onerror=function(){};
  ws.onmessage=function(ev){
    try{var m=JSON.parse(ev.data)}catch(e){return}
    if(m.event==="update"){applyUpdate(m.id,m.value)}
    else if(m.event==="heartbeat"&&m.system){renderSystem(m.system)}
    else if(m.event==="log"){addLog(m.severity,m.message)}
    else if(m.event==="ota_progress"){otaProgress(m.percent)}
    else if(m.event==="ota_delivered"){otaDelivered()}
  };
}
function scheduleReconnect(){clearTimeout(reconnectT);reconnectT=setTimeout(connectWs,2000)}

/* ---------- log panel ---------- */
var logState={open:false,paused:false,lines:[],unread:0,MAX:200};
function pad2(n){return n<10?"0"+n:""+n}
function logTime(){var d=new Date();return pad2(d.getHours())+":"+pad2(d.getMinutes())+":"+pad2(d.getSeconds())}
function addLog(severity,message){
  var sev=(severity==="warn"||severity==="error")?severity:"info";
  var entry={t:logTime(),s:sev,m:""+(message==null?"":message)};
  logState.lines.push(entry);
  if(logState.lines.length>logState.MAX)logState.lines.shift();
  if(logState.open&&!logState.paused){renderLogLine(entry);trimLogDom()}
  else{logState.unread++;updateLogChip()}
}
function renderLogLine(e){
  var body=$("logBody");
  var empty=body.querySelector(".empty");if(empty)empty.remove();
  var ln=document.createElement("div");ln.className="ln";
  var t=document.createElement("span");t.className="t";t.textContent=e.t;
  var s=document.createElement("span");s.className="s "+e.s;s.textContent=e.s;
  var m=document.createElement("span");m.className="m";m.textContent=e.m;
  ln.appendChild(t);ln.appendChild(s);ln.appendChild(m);
  body.appendChild(ln);
  body.scrollTop=body.scrollHeight;
}
function trimLogDom(){var body=$("logBody"),lns=body.querySelectorAll(".ln");if(lns.length>logState.MAX){var n=lns.length-logState.MAX;for(var i=0;i<n;i++)lns[i].remove()}}
function rerenderLog(){
  var body=$("logBody");body.innerHTML="";
  if(!logState.lines.length){body.innerHTML='<div class="empty">Waiting for log events…</div>';return}
  logState.lines.forEach(renderLogLine);
}
function updateLogChip(){
  var ct=$("logCt");
  if(logState.unread>0&&!logState.open){ct.textContent=logState.unread>99?"99+":(""+logState.unread);ct.classList.add("show")}
  else{ct.classList.remove("show")}
}
function toggleLogPanel(){
  logState.open=!logState.open;
  $("logPanel").classList.toggle("open",logState.open);
  $("logToggle").classList.toggle("active",logState.open);
  $("logToggle").setAttribute("aria-pressed",logState.open?"true":"false");
  if(logState.open){logState.unread=0;updateLogChip();rerenderLog()}
}
$("logToggle").addEventListener("click",toggleLogPanel);
$("logPause").addEventListener("click",function(){
  logState.paused=!logState.paused;
  this.textContent=logState.paused?"Resume":"Pause";
  this.classList.toggle("on",logState.paused);
  if(!logState.paused){logState.unread=0;updateLogChip();rerenderLog()}
});
$("logClear").addEventListener("click",function(){logState.lines=[];logState.unread=0;updateLogChip();rerenderLog()});

/* ---------- OTA overlay ---------- */
var ota={shown:false,failed:false,timer:null};
function otaShow(){
  /* Reset state every call so a fresh OTA after a previous failure starts clean */
  ota.failed=false;
  if(ota.timer){clearTimeout(ota.timer);ota.timer=null}
  var o=$("otaOverlay");o.classList.remove("fail");
  if(!ota.shown){ota.shown=true;o.classList.add("show")}
  $("otaTitle").textContent="Updating firmware";
  $("otaIc").textContent="↑";
  $("otaMsg").textContent="Please keep this page open. Device will reboot when done.";
  $("otaBar").style.width="0%";
  $("otaPct").textContent="starting…";
}
function otaHide(){
  ota.shown=false;ota.failed=false;
  $("otaOverlay").classList.remove("show","fail");
  if(ota.timer){clearTimeout(ota.timer);ota.timer=null}
}
function otaProgress(percent){
  if(percent===-1){
    otaShow();
    ota.failed=true;
    $("otaOverlay").classList.add("fail");
    $("otaIc").textContent="!";
    $("otaTitle").textContent="Update failed";
    $("otaMsg").textContent="Device rejected the update. It is still running the old firmware.";
    $("otaPct").textContent="error";
    return;
  }
  otaShow();
  var p=Math.max(0,Math.min(100,percent|0));
  $("otaBar").style.width=p+"%";
  $("otaPct").textContent=p+"%";
}
function otaDelivered(){
  /* Firmware written to flash — device will reboot momentarily */
  otaShow();
  $("otaBar").style.width="100%";
  $("otaPct").textContent="received";
  $("otaTitle").textContent="Firmware received";
  $("otaMsg").textContent="Update written. Device will reboot now…";
  $("otaIc").textContent="✓";
}
function otaReboot(){
  /* Called when WS closes during an active update — device is rebooting */
  $("otaTitle").textContent="Restarting device";
  $("otaMsg").textContent="The device is rebooting with the new firmware…";
  $("otaPct").textContent="rebooting";
  $("otaBar").style.width="100%";
  if(ota.timer)clearTimeout(ota.timer);
  ota.timer=setTimeout(function(){location.reload()},6000);
}
$("otaDismiss").addEventListener("click",otaHide);
$("otaOverlay").addEventListener("click",function(e){if(e.target===this&&ota.failed)otaHide()});

/* ---------- Add to Home Screen hint ---------- */
function maybeShowPwaHint(){
  try{
    if(localStorage.getItem("trellis_pwa_hint_seen")==="1")return;
    if(window.matchMedia&&window.matchMedia("(display-mode: standalone)").matches)return;
    if(window.navigator.standalone)return; /* iOS */
    if(window.innerWidth>=768)return; /* mobile only */
    var ua=navigator.userAgent||"";
    var isIOS=/iPad|iPhone|iPod/.test(ua)&&!window.MSStream;
    var isAndroid=/Android/.test(ua);
    if(!isIOS&&!isAndroid)return;
    if(isIOS){$("pwaSub").textContent="Tap Share, then Add to Home Screen"}
    else{$("pwaSub").textContent="Tap menu (⋮), then Add to Home Screen"}
    setTimeout(function(){$("pwaHint").classList.add("show")},1200);
  }catch(e){}
}
$("pwaClose").addEventListener("click",function(){
  $("pwaHint").classList.remove("show");
  try{localStorage.setItem("trellis_pwa_hint_seen","1")}catch(e){}
});

loadInfo();
maybeShowPwaHint();
})();
</script>
</body>
</html>)TWUI";
static const char TRELLIS_WEB_UI_HTML_HASH[] = "fb4c53df7924588f";

#endif
