// Auto-generated from src/web_ui.html by scripts/build_web_ui_header.py
// Do not edit this file by hand — edit web_ui.html and regenerate.
#ifndef TRELLIS_WEB_UI_HTML_H
#define TRELLIS_WEB_UI_HTML_H
#include <Arduino.h>

static const char TRELLIS_WEB_UI_HTML[] PROGMEM = R"TWUI(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="dark">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="mobile-web-app-capable" content="yes">
<meta name="theme-color" content="#0b0d10">
<title>Trellis</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%235eead4'/%3E%3Ctext x='16' y='22' font-family='system-ui,sans-serif' font-size='20' font-weight='800' text-anchor='middle' fill='%23062c2e'%3ET%3C/text%3E%3C/svg%3E">
<link rel="apple-touch-icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 180 180'%3E%3Crect width='180' height='180' rx='40' fill='%235eead4'/%3E%3Ctext x='90' y='124' font-family='system-ui,sans-serif' font-size='112' font-weight='800' text-anchor='middle' fill='%23062c2e'%3ET%3C/text%3E%3C/svg%3E">
<link rel="manifest" href="/manifest.webmanifest">
<style>
:root{
  --bg:#0b0d10;--panel:#15181d;--panel2:#1c2026;--bd:#252a32;
  --fg:#e7ecf3;--mut:#8a93a3;--acc:#5eead4;--accd:#2dd4bf;
  --ok:#22c55e;--warn:#f59e0b;--err:#ef4444;--shadow:0 1px 0 #ffffff08 inset,0 8px 24px #00000040;
}
*{box-sizing:border-box}
html,body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.45 -apple-system,system-ui,Segoe UI,Roboto,sans-serif;-webkit-font-smoothing:antialiased;overflow-x:hidden}
a{color:var(--acc)}
.wrap{max-width:720px;margin:0 auto;padding:max(16px,env(safe-area-inset-top)) 16px max(24px,env(safe-area-inset-bottom))}
header{display:flex;align-items:center;gap:12px;margin:8px 0 18px;min-width:0}
header .logo{width:34px;height:34px;border-radius:9px;background:linear-gradient(135deg,var(--acc),#0ea5b1);display:grid;place-items:center;font-weight:800;color:#06292a;box-shadow:var(--shadow);flex:none}
header .ttl{flex:1;min-width:0;overflow:hidden}
header h1{font-size:18px;margin:0;font-weight:700;letter-spacing:.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
header .sub{font-size:12px;color:var(--mut);margin-top:1px;display:flex;gap:6px;align-items:center;flex-wrap:wrap}
.dot{width:8px;height:8px;border-radius:50%;background:var(--mut);box-shadow:0 0 0 3px #ffffff08}
.dot.on{background:var(--ok);box-shadow:0 0 0 3px #22c55e22}
.dot.off{background:var(--err);box-shadow:0 0 0 3px #ef444422}
.badge{font-size:10px;text-transform:uppercase;letter-spacing:.6px;color:var(--mut);border:1px solid var(--bd);padding:2px 6px;border-radius:999px}
.sys{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:18px}
.sys div{background:var(--panel);border:1px solid var(--bd);border-radius:12px;padding:10px 12px;box-shadow:var(--shadow)}
.sys b{display:block;font-size:11px;color:var(--mut);font-weight:500;text-transform:uppercase;letter-spacing:.5px;margin-bottom:3px}
.sys span{font-size:15px;font-weight:600;font-variant-numeric:tabular-nums}
.grid{display:grid;grid-template-columns:1fr;gap:12px}
@media(min-width:560px){.grid{grid-template-columns:1fr 1fr}.full{grid-column:1/-1}}
.card{background:var(--panel);border:1px solid var(--bd);border-radius:14px;padding:14px 16px;box-shadow:var(--shadow);transition:border-color .15s}
.card:hover{border-color:#2f3540}
.card h3{margin:0 0 4px;font-size:11px;text-transform:uppercase;letter-spacing:.6px;color:var(--mut);font-weight:600}
.row{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:6px}
.val{font-size:30px;font-weight:700;font-variant-numeric:tabular-nums;line-height:1.1}
.unit{font-size:14px;color:var(--mut);margin-left:4px;font-weight:500}
/* switch */
.sw{position:relative;width:54px;height:30px;flex:none}
.sw input{opacity:0;width:0;height:0}
.sw .slot{position:absolute;inset:0;background:#2a2f38;border-radius:999px;transition:.2s;cursor:pointer;border:1px solid var(--bd)}
.sw .slot:before{content:"";position:absolute;left:3px;top:3px;width:22px;height:22px;background:#cbd5e1;border-radius:50%;transition:.2s;box-shadow:0 1px 4px #0006}
.sw input:checked+.slot{background:var(--accd);border-color:var(--accd)}
.sw input:checked+.slot:before{transform:translateX(24px);background:#fff}
/* slider */
input[type=range]{-webkit-appearance:none;appearance:none;width:100%;height:6px;background:#2a2f38;border-radius:999px;outline:none;margin:10px 0 4px}
input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:20px;height:20px;border-radius:50%;background:var(--acc);cursor:pointer;box-shadow:0 0 0 4px #5eead422,0 2px 6px #0008;border:none}
input[type=range]::-moz-range-thumb{width:20px;height:20px;border-radius:50%;background:var(--acc);cursor:pointer;border:none;box-shadow:0 0 0 4px #5eead422}
/* color */
input[type=color]{-webkit-appearance:none;appearance:none;width:48px;height:48px;border:1px solid var(--bd);border-radius:12px;background:transparent;padding:0;cursor:pointer}
input[type=color]::-webkit-color-swatch-wrapper{padding:3px}
input[type=color]::-webkit-color-swatch{border:none;border-radius:9px}
input[type=color]::-moz-color-swatch{border:none;border-radius:9px}
.hex{font-family:ui-monospace,Menlo,monospace;font-size:13px;color:var(--mut);letter-spacing:.5px}
/* text */
.tx{display:flex;gap:8px;margin-top:8px}
.tx input{flex:1;background:var(--panel2);border:1px solid var(--bd);color:var(--fg);border-radius:10px;padding:9px 12px;font:inherit;outline:none;transition:border-color .15s}
.tx input:focus{border-color:var(--acc)}
.tx button{background:var(--accd);color:#06292a;border:none;border-radius:10px;padding:0 14px;font-weight:700;cursor:pointer;font:inherit;transition:filter .15s}
.tx button:hover{filter:brightness(1.1)}
.tx button:active{transform:translateY(1px)}
.tdisp{font-size:18px;font-weight:600;margin-top:6px;word-break:break-word}
.empty{color:var(--mut);text-align:center;padding:36px 16px;border:1px dashed var(--bd);border-radius:14px}
footer{margin-top:24px;text-align:center;color:var(--mut);font-size:11px}
footer a{text-decoration:none}
.toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%) translateY(60px);background:var(--panel2);border:1px solid var(--bd);color:var(--fg);padding:9px 16px;border-radius:999px;font-size:13px;box-shadow:0 8px 24px #000a;opacity:0;transition:.25s;pointer-events:none;z-index:50}
.toast.show{opacity:1;transform:translateX(-50%) translateY(0)}
/* header chips (logs toggle) */
.chip{display:inline-flex;align-items:center;gap:5px;background:var(--panel2);border:1px solid var(--bd);color:var(--fg);font:600 11px/1 -apple-system,system-ui,sans-serif;text-transform:uppercase;letter-spacing:.6px;padding:5px 9px;border-radius:999px;cursor:pointer;transition:border-color .15s,background .15s;flex:none}
.chip:hover{border-color:#3a4150;background:#1f242c}
.chip.active{border-color:var(--acc);background:#5eead412;color:var(--acc)}
.chip .ind{display:inline-block;width:5px;height:5px;border-radius:50%;background:var(--mut)}
.chip.active .ind{background:var(--acc)}
.chip .ct{background:var(--acc);color:#06292a;font-size:10px;font-weight:800;padding:1px 5px;border-radius:999px;min-width:14px;text-align:center;display:none}
.chip .ct.show{display:inline-block}
/* log panel */
.logp{margin-top:14px;background:var(--panel);border:1px solid var(--bd);border-radius:14px;box-shadow:var(--shadow);overflow:hidden;display:none}
.logp.open{display:block}
.logp .lh{display:flex;align-items:center;gap:8px;padding:10px 14px;border-bottom:1px solid var(--bd);background:var(--panel2)}
.logp .lh b{font-size:11px;text-transform:uppercase;letter-spacing:.6px;color:var(--mut);font-weight:600;flex:1}
.logp .lh button{background:transparent;border:1px solid var(--bd);color:var(--mut);font:600 10px/1 -apple-system,system-ui,sans-serif;text-transform:uppercase;letter-spacing:.5px;padding:5px 9px;border-radius:7px;cursor:pointer;transition:.15s}
.logp .lh button:hover{color:var(--fg);border-color:#3a4150}
.logp .lh button.on{color:var(--acc);border-color:var(--acc)}
.logp .lb{max-height:240px;overflow-y:auto;font:12px/1.55 ui-monospace,Menlo,Consolas,monospace;padding:8px 14px}
.logp .lb .ln{padding:2px 0;display:flex;gap:8px;border-top:1px solid #ffffff05;word-break:break-word}
.logp .lb .ln:first-child{border-top:none}
.logp .lb .t{color:var(--mut);flex:none;font-variant-numeric:tabular-nums}
.logp .lb .s{flex:none;font-weight:700;text-transform:uppercase;font-size:10px;padding:1px 5px;border-radius:4px;align-self:flex-start;margin-top:1px}
.logp .lb .s.info{background:#5eead418;color:var(--acc)}
.logp .lb .s.warn{background:#f59e0b1f;color:var(--warn)}
.logp .lb .s.error{background:#ef44441f;color:var(--err)}
.logp .lb .m{color:var(--fg);flex:1;min-width:0;white-space:pre-wrap}
.logp .lb .empty{color:var(--mut);text-align:center;padding:20px 8px;border:none}
/* OTA overlay */
.ota{position:fixed;inset:0;background:#000000c8;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px);display:none;align-items:center;justify-content:center;z-index:100;padding:20px;animation:fade .2s ease}
.ota.show{display:flex}
@keyframes fade{from{opacity:0}to{opacity:1}}
.ota .box{background:var(--panel);border:1px solid var(--bd);border-radius:16px;padding:24px;width:100%;max-width:340px;box-shadow:0 24px 60px #000c;text-align:center}
.ota .ic{width:48px;height:48px;border-radius:14px;background:linear-gradient(135deg,var(--acc),#0ea5b1);display:inline-grid;place-items:center;margin-bottom:14px;color:#06292a;font-size:24px}
.ota.fail .ic{background:linear-gradient(135deg,#ef4444,#b91c1c);color:#fff}
.ota h2{margin:0 0 4px;font-size:17px;font-weight:700}
.ota p{margin:0 0 16px;font-size:13px;color:var(--mut)}
.ota .bar{width:100%;height:8px;background:#2a2f38;border-radius:999px;overflow:hidden;margin-bottom:10px}
.ota .bar i{display:block;height:100%;width:0%;background:linear-gradient(90deg,var(--acc),var(--accd));transition:width .3s;border-radius:999px}
.ota.fail .bar i{background:var(--err);width:100%}
.ota .pct{font-size:11px;color:var(--mut);font-variant-numeric:tabular-nums;text-transform:uppercase;letter-spacing:.6px}
.ota .dis{margin-top:14px;background:transparent;border:1px solid var(--bd);color:var(--mut);padding:7px 14px;border-radius:8px;font:600 11px/1 -apple-system,system-ui,sans-serif;text-transform:uppercase;letter-spacing:.5px;cursor:pointer;display:none}
.ota.fail .dis{display:inline-block;color:var(--fg);border-color:#3a4150}
.ota.fail .dis:hover{border-color:var(--err);color:var(--err)}
/* PWA install hint (mobile only) */
.pwa{position:fixed;left:12px;right:12px;bottom:max(12px,env(safe-area-inset-bottom));background:var(--panel2);border:1px solid var(--bd);border-radius:14px;padding:14px 16px;box-shadow:0 12px 32px #000a;display:none;align-items:center;gap:12px;z-index:60;animation:rise .3s ease}
.pwa.show{display:flex}
@keyframes rise{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}
.pwa .pi{width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,var(--acc),#0ea5b1);display:grid;place-items:center;color:#06292a;font-weight:800;flex:none}
.pwa .pt{flex:1;min-width:0}
.pwa .pt b{display:block;font-size:13px;font-weight:600;margin-bottom:1px}
.pwa .pt span{font-size:11px;color:var(--mut)}
.pwa .px{background:transparent;border:none;color:var(--mut);font-size:20px;line-height:1;padding:4px 8px;cursor:pointer;border-radius:6px;flex:none}
.pwa .px:hover{color:var(--fg);background:#ffffff0a}
.pwa .pgo{display:none;background:var(--accd);color:#06292a;border:none;border-radius:9px;padding:7px 12px;font:700 12px/1 -apple-system,system-ui,sans-serif;cursor:pointer;flex:none;transition:filter .15s}
.pwa .pgo:hover{filter:brightness(1.1)}
.pwa .pgo.show{display:inline-block}
/* peers (LAN-wide control) */
.peers{margin-top:24px;display:none}
.peers.show{display:block}
.peers .ph{margin:0 0 10px;font-size:11px;text-transform:uppercase;letter-spacing:.6px;color:var(--mut);font-weight:600;display:flex;align-items:center;gap:8px}
.peer{background:var(--panel2);border:1px solid var(--bd);border-radius:14px;margin-bottom:10px;overflow:hidden;box-shadow:var(--shadow);transition:border-color .15s}
.peer:hover{border-color:#2f3540}
.peer .head{display:flex;align-items:center;gap:12px;padding:12px 14px;cursor:pointer;user-select:none}
.peer .head:hover{background:#1f242c}
.peer .head .pn{flex:1;font-weight:600;font-size:14px;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.peer .head .pmeta{font-size:11px;color:var(--mut);font-variant-numeric:tabular-nums}
.peer .head .chev{color:var(--mut);font-size:16px;line-height:1;transition:transform .2s;flex:none}
.peer.open .head .chev{transform:rotate(90deg)}
.peer .body{display:none;padding:0 14px 14px;border-top:1px solid var(--bd)}
.peer.open .body{display:block}
.peer .bgrid{display:grid;grid-template-columns:1fr;gap:10px;margin-top:12px}
@media(min-width:560px){.peer .bgrid{grid-template-columns:1fr 1fr}.peer .bgrid .full{grid-column:1/-1}}
.peer .pmsg{color:var(--mut);font-size:12px;padding:14px 0 4px}
.peer .pmsg.err{color:var(--err)}
/* scenes + schedules — on-device automation surface */
.auto{margin-top:24px}
.auto h2{margin:0 0 10px;font-size:11px;text-transform:uppercase;letter-spacing:.6px;color:var(--mut);font-weight:600;display:flex;align-items:center;gap:8px}
.auto h2 .ct{font-weight:500;color:var(--mut);font-size:10px;letter-spacing:.4px}
.row-card{background:var(--panel2);border:1px solid var(--bd);border-radius:12px;padding:10px 12px;margin-bottom:8px;display:flex;align-items:center;gap:10px;box-shadow:var(--shadow);transition:border-color .15s}
.row-card:hover{border-color:#2f3540}
.row-card .lbl{flex:1;min-width:0;overflow:hidden}
.row-card .lbl b{display:block;font-size:13px;font-weight:600;color:var(--fg);text-overflow:ellipsis;overflow:hidden;white-space:nowrap}
.row-card .lbl span{display:block;font-size:11px;color:var(--mut);font-variant-numeric:tabular-nums;margin-top:1px}
.row-card .acts{display:flex;gap:6px;flex:none}
.btn-sm{background:var(--panel);border:1px solid var(--bd);color:var(--fg);font:600 11px/1 -apple-system,system-ui,sans-serif;text-transform:uppercase;letter-spacing:.5px;padding:6px 10px;border-radius:7px;cursor:pointer;transition:.15s}
.btn-sm:hover{border-color:#3a4150;background:#1f242c}
.btn-sm.go{background:var(--accd);color:#06292a;border-color:var(--accd);font-weight:700}
.btn-sm.go:hover{filter:brightness(1.1)}
.btn-sm.danger:hover{border-color:var(--err);color:var(--err)}
.add-form{background:var(--panel);border:1px solid var(--bd);border-radius:12px;padding:12px;margin-top:6px;box-shadow:var(--shadow)}
.add-form .frow{display:flex;gap:8px;align-items:center;margin-bottom:8px;flex-wrap:wrap}
.add-form .frow:last-child{margin-bottom:0}
.add-form input[type=text],.add-form input[type=time],.add-form select{background:var(--panel2);border:1px solid var(--bd);color:var(--fg);border-radius:8px;padding:8px 10px;font:inherit;outline:none;flex:1;min-width:0;transition:border-color .15s}
.add-form input[type=text]:focus,.add-form input[type=time]:focus,.add-form select:focus{border-color:var(--acc)}
.add-form input[type=time]{flex:0 0 110px;font-variant-numeric:tabular-nums}
.add-form .lab{font-size:11px;text-transform:uppercase;letter-spacing:.5px;color:var(--mut);font-weight:600;flex:0 0 auto}
.dow{display:flex;gap:4px;flex:1;flex-wrap:wrap}
.dow label{display:inline-flex;align-items:center;justify-content:center;min-width:30px;height:28px;padding:0 7px;background:var(--panel2);border:1px solid var(--bd);border-radius:7px;font:600 11px/1 -apple-system,system-ui,sans-serif;text-transform:uppercase;letter-spacing:.4px;color:var(--mut);cursor:pointer;transition:.12s;user-select:none}
.dow label:hover{border-color:#3a4150;color:var(--fg)}
.dow input{position:absolute;opacity:0;width:0;height:0;pointer-events:none}
.dow label.on{background:#5eead418;color:var(--acc);border-color:var(--acc)}
.empty-mini{color:var(--mut);font-size:12px;text-align:center;padding:14px 8px;border:1px dashed var(--bd);border-radius:10px;margin-bottom:8px}
</style>
</head>
<body>
<div class="wrap">
  <header>
    <div class="logo">T</div>
    <div class="ttl">
      <h1 id="name">Trellis Device</h1>
      <div class="sub">
        <span class="dot" id="dot"></span>
        <span id="status">connecting…</span>
        <span class="badge" id="plat"></span>
        <span class="badge" id="fw"></span>
      </div>
    </div>
    <button class="chip" id="logToggle" type="button" aria-pressed="false" aria-label="Toggle log panel"><span class="ind"></span>Logs<span class="ct" id="logCt">0</span></button>
  </header>
  <div class="sys">
    <div><b>Signal</b><span id="rssi">—</span></div>
    <div><b>Free heap</b><span id="heap">—</span></div>
    <div><b>Uptime</b><span id="up">—</span></div>
  </div>
  <div class="grid" id="grid"></div>
  <section class="auto" id="scenesSec" aria-label="Scenes">
    <h2>Scenes <span class="ct" id="scenesCt"></span></h2>
    <div id="scenesList"></div>
    <div class="add-form" id="sceneAdd">
      <div class="frow">
        <input type="text" id="sceneName" placeholder="Name this scene…" maxlength="32">
        <button type="button" class="btn-sm go" id="sceneCapture">Capture current state</button>
      </div>
    </div>
  </section>
  <section class="auto" id="schedSec" aria-label="Schedules">
    <h2>Schedules <span class="ct" id="schedCt"></span></h2>
    <div id="schedList"></div>
    <div class="add-form" id="schedAdd">
      <div class="frow">
        <span class="lab">Scene</span>
        <select id="schedScene"></select>
        <span class="lab">At</span>
        <input type="time" id="schedTime" value="08:00">
      </div>
      <div class="frow">
        <span class="lab">Days</span>
        <div class="dow" id="schedDow"></div>
        <button type="button" class="btn-sm go" id="schedAddBtn">Add schedule</button>
      </div>
    </div>
  </section>
  <section class="peers" id="peers" aria-label="Other Trellis devices on this network">
    <h2 class="ph">Devices on this network</h2>
    <div id="peerList"></div>
  </section>
  <section class="logp" id="logPanel" aria-label="Device logs">
    <div class="lh">
      <b>Live Logs</b>
      <button type="button" id="logPause">Pause</button>
      <button type="button" id="logClear">Clear</button>
    </div>
    <div class="lb" id="logBody"><div class="empty">Waiting for log events…</div></div>
  </section>
  <footer>Powered by <a href="https://github.com/ovexro/trellis" target="_blank" rel="noopener">Trellis</a> · <span id="id">—</span></footer>
</div>
<div class="toast" id="toast"></div>
<div class="ota" id="otaOverlay" role="dialog" aria-modal="true" aria-labelledby="otaTitle">
  <div class="box">
    <div class="ic" id="otaIc">↑</div>
    <h2 id="otaTitle">Updating firmware</h2>
    <p id="otaMsg">Please keep this page open. Device will reboot when done.</p>
    <div class="bar"><i id="otaBar"></i></div>
    <div class="pct" id="otaPct">starting…</div>
    <button type="button" class="dis" id="otaDismiss">Dismiss</button>
  </div>
</div>
<div class="pwa" id="pwaHint" role="dialog" aria-label="Install hint">
  <div class="pi">T</div>
  <div class="pt"><b id="pwaTitle">Add to Home Screen</b><span id="pwaSub">Install for one-tap access</span></div>
  <button type="button" class="pgo" id="pwaInstall" aria-label="Install app">Install</button>
  <button type="button" class="px" id="pwaClose" aria-label="Dismiss">×</button>
</div>
<script>
(function(){
var host=location.hostname,wsPort=(parseInt(location.port||"80",10))+1,ws,reconnectT,caps={},info=null;
var $=function(s){return document.getElementById(s)};
function esc(s){return(""+s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function toast(t){var e=$("toast");e.textContent=t;e.classList.add("show");clearTimeout(toast._t);toast._t=setTimeout(function(){e.classList.remove("show")},1800)}
function setStatus(state,txt){var d=$("dot"),s=$("status");d.className="dot "+state;s.textContent=txt}
function fmtUp(s){if(s<60)return s+"s";var m=Math.floor(s/60);if(m<60)return m+"m";var h=Math.floor(m/60);if(h<48)return h+"h "+(m%60)+"m";return Math.floor(h/24)+"d "+(h%24)+"h"}
function fmtHeap(b){if(b>=1048576)return(b/1048576).toFixed(1)+" MB";if(b>=1024)return(b/1024).toFixed(0)+" KB";return b+" B"}
function fmtRssi(r){return r+" dBm"}
function send(id,value){if(!ws||ws.readyState!==1){toast("Not connected");return}ws.send(JSON.stringify({command:"set",id:id,value:value}))}
function renderSystem(s){if(!s)return;if(s.rssi!=null)$("rssi").textContent=fmtRssi(s.rssi);if(s.heap_free!=null)$("heap").textContent=fmtHeap(s.heap_free);if(s.uptime_s!=null)$("up").textContent=fmtUp(s.uptime_s)}
function buildCard(c){
  var card=document.createElement("div");card.className="card";
  if(c.type==="text")card.classList.add("full");
  var h=document.createElement("h3");h.textContent=c.label||c.id;card.appendChild(h);
  if(c.type==="switch"){
    var row=document.createElement("div");row.className="row";
    var v=document.createElement("div");v.className="val";v.id="v_"+c.id;v.textContent=c.value?"On":"Off";
    var sw=document.createElement("label");sw.className="sw";
    sw.innerHTML='<input type="checkbox" '+(c.value?"checked":"")+'><span class="slot"></span>';
    sw.querySelector("input").addEventListener("change",function(e){send(c.id,e.target.checked)});
    row.appendChild(v);row.appendChild(sw);card.appendChild(row);
  }else if(c.type==="slider"){
    var row2=document.createElement("div");row2.className="row";
    var unitSpan='<span class="unit">'+esc(c.min)+"–"+esc(c.max)+"</span>";
    var vv=document.createElement("div");vv.className="val";vv.id="v_"+c.id;vv.innerHTML=Math.round(c.value)+unitSpan;
    row2.appendChild(vv);card.appendChild(row2);
    var r=document.createElement("input");r.type="range";r.min=c.min;r.max=c.max;r.value=c.value;r.step=(c.max-c.min)>10?1:0.1;
    var commit;
    r.addEventListener("input",function(e){vv.innerHTML=Math.round(e.target.value)+unitSpan;clearTimeout(commit);commit=setTimeout(function(){send(c.id,parseFloat(e.target.value))},80)});
    card.appendChild(r);
  }else if(c.type==="sensor"){
    var row3=document.createElement("div");row3.className="row";
    var sv=document.createElement("div");sv.className="val";sv.id="v_"+c.id;
    var unitS=c.unit?'<span class="unit">'+esc(c.unit)+"</span>":"";
    sv.innerHTML=(typeof c.value==="number"?(Math.abs(c.value)<10?c.value.toFixed(2):c.value.toFixed(1)):"—")+unitS;
    sv.dataset.unit=unitS;
    row3.appendChild(sv);card.appendChild(row3);
  }else if(c.type==="color"){
    var row4=document.createElement("div");row4.className="row";
    var cp=document.createElement("input");cp.type="color";cp.value=c.value||"#000000";cp.id="v_"+c.id;
    var hx=document.createElement("div");hx.className="hex";hx.id="hx_"+c.id;hx.textContent=(c.value||"#000000").toUpperCase();
    var commit2;
    cp.addEventListener("input",function(e){hx.textContent=e.target.value.toUpperCase();clearTimeout(commit2);commit2=setTimeout(function(){send(c.id,e.target.value)},80)});
    row4.appendChild(hx);row4.appendChild(cp);card.appendChild(row4);
  }else if(c.type==="text"){
    var disp=document.createElement("div");disp.className="tdisp";disp.id="v_"+c.id;disp.textContent=c.value||"";
    card.appendChild(disp);
    var bx=document.createElement("div");bx.className="tx";
    var ti=document.createElement("input");ti.type="text";ti.placeholder="Enter text…";ti.maxLength=31;
    var bt=document.createElement("button");bt.textContent="Set";
    function go(){if(!ti.value)return;send(c.id,ti.value);ti.value=""}
    bt.addEventListener("click",go);
    ti.addEventListener("keydown",function(e){if(e.key==="Enter")go()});
    bx.appendChild(ti);bx.appendChild(bt);card.appendChild(bx);
  }
  return card;
}
function applyUpdate(id,value){
  var c=caps[id];if(!c)return;
  var el=$("v_"+id);if(!el)return;
  if(c.type==="switch"){el.textContent=value?"On":"Off";var i=el.parentNode.querySelector("input");if(i)i.checked=!!value}
  else if(c.type==="slider"){el.innerHTML=Math.round(value)+'<span class="unit">'+esc(c.min)+"–"+esc(c.max)+"</span>";var rr=el.parentNode.parentNode.querySelector('input[type=range]');if(rr&&document.activeElement!==rr)rr.value=value}
  else if(c.type==="sensor"){el.innerHTML=(typeof value==="number"?(Math.abs(value)<10?value.toFixed(2):value.toFixed(1)):esc(value))+(el.dataset.unit||"")}
  else if(c.type==="color"){if(document.activeElement!==el)el.value=value;var hh=$("hx_"+id);if(hh)hh.textContent=(""+value).toUpperCase()}
  else if(c.type==="text"){el.textContent=value}
}
function loadInfo(){
  fetch("/api/info").then(function(r){return r.json()}).then(function(d){
    info=d;
    $("name").textContent=d.name||"Trellis Device";document.title=(d.name||"Trellis")+" · Trellis";
    $("plat").textContent=d.platform||"";
    $("fw").textContent=d.firmware?"v"+d.firmware:"";
    $("id").textContent=d.id||"";
    renderSystem(d.system);
    var g=$("grid");g.innerHTML="";caps={};
    if(!d.capabilities||!d.capabilities.length){g.innerHTML='<div class="empty full">No capabilities exposed yet.</div>';}
    else{d.capabilities.forEach(function(c){caps[c.id]=c;g.appendChild(buildCard(c))});}
    connectWs();
  }).catch(function(){setStatus("off","unreachable");setTimeout(loadInfo,3000)});
}
function connectWs(){
  try{ws=new WebSocket("ws://"+host+":"+wsPort+"/")}catch(e){return scheduleReconnect()}
  ws.onopen=function(){setStatus("on","live");if(ota.shown&&!ota.failed){location.reload()}};
  ws.onclose=function(){setStatus("off","reconnecting…");if(ota.shown&&!ota.failed){otaReboot()}scheduleReconnect()};
  ws.onerror=function(){};
  ws.onmessage=function(ev){
    try{var m=JSON.parse(ev.data)}catch(e){return}
    if(m.event==="update"){applyUpdate(m.id,m.value)}
    else if(m.event==="heartbeat"&&m.system){renderSystem(m.system)}
    else if(m.event==="log"){addLog(m.severity,m.message)}
    else if(m.event==="ota_progress"){otaProgress(m.percent)}
    else if(m.event==="ota_delivered"){otaDelivered()}
  };
}
function scheduleReconnect(){clearTimeout(reconnectT);reconnectT=setTimeout(connectWs,2000)}

/* ---------- peers (LAN-wide control) ----------
   Each peer is collapsed by default. On expand we fetch the peer's
   /api/info, render its capabilities, and open a WS to the peer for
   live updates and commands. Collapse closes the WS so we don't hold N
   sockets open across all discovered devices. */
var peers={};
function loadPeers(){
  fetch("/api/peers").then(function(r){return r.json()}).then(function(arr){
    var sec=$("peers"),list=$("peerList");
    if(!Array.isArray(arr))arr=[];
    var seen={};
    arr.forEach(function(p){
      if(!p||!p.id)return;
      seen[p.id]=true;
      var s=peers[p.id];
      if(!s){peers[p.id]={peer:p,expanded:false,caps:{},ws:null};list.appendChild(buildPeerCard(p))}
      else{s.peer=p}
    });
    Object.keys(peers).forEach(function(id){
      if(seen[id])return;
      closePeerWs(id);
      var el=document.getElementById("peer_"+id);if(el)el.remove();
      delete peers[id];
    });
    sec.classList.toggle("show",Object.keys(peers).length>0);
  }).catch(function(){});
}
function buildPeerCard(p){
  var card=document.createElement("div");card.className="peer";card.id="peer_"+p.id;
  var head=document.createElement("div");head.className="head";
  var nm=document.createElement("div");nm.className="pn";nm.textContent=p.name||p.id;
  var meta=document.createElement("div");meta.className="pmeta";meta.textContent=p.host+":"+p.port;
  var chev=document.createElement("span");chev.className="chev";chev.textContent="›";
  head.appendChild(nm);head.appendChild(meta);head.appendChild(chev);
  head.addEventListener("click",function(){togglePeer(p.id)});
  card.appendChild(head);
  var body=document.createElement("div");body.className="body";
  card.appendChild(body);
  return card;
}
function togglePeer(id){
  var s=peers[id];if(!s)return;
  var card=document.getElementById("peer_"+id);if(!card)return;
  s.expanded=!s.expanded;
  card.classList.toggle("open",s.expanded);
  if(s.expanded)loadPeerInfo(id);
  else closePeerWs(id);
}
function loadPeerInfo(id){
  var s=peers[id];if(!s)return;
  var p=s.peer,card=document.getElementById("peer_"+id);if(!card)return;
  var body=card.querySelector(".body");
  body.innerHTML='<div class="pmsg">Loading capabilities…</div>';
  fetch("http://"+p.host+":"+p.port+"/api/info").then(function(r){return r.json()}).then(function(d){
    s.caps={};
    var grid=document.createElement("div");grid.className="bgrid";
    if(!d.capabilities||!d.capabilities.length){
      body.innerHTML='<div class="pmsg">This device exposes no capabilities.</div>';
      return;
    }
    d.capabilities.forEach(function(c){s.caps[c.id]=c;grid.appendChild(buildPeerCapCard(id,c))});
    body.innerHTML="";body.appendChild(grid);
    openPeerWs(id);
  }).catch(function(){
    body.innerHTML='<div class="pmsg err">Could not reach this device. It may be offline or blocking cross-origin reads.</div>';
  });
}
function buildPeerCapCard(pid,c){
  /* Mirrors buildCard but with peer-scoped DOM ids ("pv_<pid>_<capid>") and
     a peer-aware send (peerSend) so commands route to that peer's WS, not
     the local device's. Kept separate to avoid touching the local renderer. */
  var card=document.createElement("div");card.className="card";
  if(c.type==="text")card.classList.add("full");
  var h=document.createElement("h3");h.textContent=c.label||c.id;card.appendChild(h);
  var vid="pv_"+pid+"_"+c.id;
  if(c.type==="switch"){
    var row=document.createElement("div");row.className="row";
    var v=document.createElement("div");v.className="val";v.id=vid;v.textContent=c.value?"On":"Off";
    var sw=document.createElement("label");sw.className="sw";
    sw.innerHTML='<input type="checkbox" '+(c.value?"checked":"")+'><span class="slot"></span>';
    sw.querySelector("input").addEventListener("change",function(e){peerSend(pid,c.id,e.target.checked)});
    row.appendChild(v);row.appendChild(sw);card.appendChild(row);
  }else if(c.type==="slider"){
    var row2=document.createElement("div");row2.className="row";
    var unitSpan='<span class="unit">'+esc(c.min)+"–"+esc(c.max)+"</span>";
    var vv=document.createElement("div");vv.className="val";vv.id=vid;vv.innerHTML=Math.round(c.value)+unitSpan;
    row2.appendChild(vv);card.appendChild(row2);
    var r=document.createElement("input");r.type="range";r.min=c.min;r.max=c.max;r.value=c.value;r.step=(c.max-c.min)>10?1:0.1;
    var commit;
    r.addEventListener("input",function(e){vv.innerHTML=Math.round(e.target.value)+unitSpan;clearTimeout(commit);commit=setTimeout(function(){peerSend(pid,c.id,parseFloat(e.target.value))},80)});
    card.appendChild(r);
  }else if(c.type==="sensor"){
    var row3=document.createElement("div");row3.className="row";
    var sv=document.createElement("div");sv.className="val";sv.id=vid;
    var unitS=c.unit?'<span class="unit">'+esc(c.unit)+"</span>":"";
    sv.innerHTML=(typeof c.value==="number"?(Math.abs(c.value)<10?c.value.toFixed(2):c.value.toFixed(1)):"—")+unitS;
    sv.dataset.unit=unitS;
    row3.appendChild(sv);card.appendChild(row3);
  }else if(c.type==="color"){
    var row4=document.createElement("div");row4.className="row";
    var cp=document.createElement("input");cp.type="color";cp.value=c.value||"#000000";cp.id=vid;
    var hx=document.createElement("div");hx.className="hex";hx.id="phx_"+pid+"_"+c.id;hx.textContent=(c.value||"#000000").toUpperCase();
    var commit2;
    cp.addEventListener("input",function(e){hx.textContent=e.target.value.toUpperCase();clearTimeout(commit2);commit2=setTimeout(function(){peerSend(pid,c.id,e.target.value)},80)});
    row4.appendChild(hx);row4.appendChild(cp);card.appendChild(row4);
  }else if(c.type==="text"){
    var disp=document.createElement("div");disp.className="tdisp";disp.id=vid;disp.textContent=c.value||"";
    card.appendChild(disp);
    var bx=document.createElement("div");bx.className="tx";
    var ti=document.createElement("input");ti.type="text";ti.placeholder="Enter text…";ti.maxLength=31;
    var bt=document.createElement("button");bt.textContent="Set";
    function go(){if(!ti.value)return;peerSend(pid,c.id,ti.value);ti.value=""}
    bt.addEventListener("click",go);
    ti.addEventListener("keydown",function(e){if(e.key==="Enter")go()});
    bx.appendChild(ti);bx.appendChild(bt);card.appendChild(bx);
  }
  return card;
}
function openPeerWs(id){
  var s=peers[id];if(!s)return;
  closePeerWs(id);
  var p=s.peer;
  try{s.ws=new WebSocket("ws://"+p.host+":"+(p.port+1)+"/")}catch(e){return}
  s.ws.onmessage=function(ev){
    try{var m=JSON.parse(ev.data)}catch(e){return}
    if(m.event==="update")peerApplyUpdate(id,m.id,m.value);
  };
  s.ws.onerror=function(){};
  s.ws.onclose=function(){};
}
function closePeerWs(id){
  var s=peers[id];if(!s||!s.ws)return;
  try{s.ws.close()}catch(e){}
  s.ws=null;
}
function peerSend(pid,capId,value){
  var s=peers[pid];if(!s||!s.ws||s.ws.readyState!==1){toast("Peer not connected");return}
  s.ws.send(JSON.stringify({command:"set",id:capId,value:value}));
}
function peerApplyUpdate(pid,capId,value){
  var s=peers[pid];if(!s)return;
  var c=s.caps[capId];if(!c)return;
  var el=document.getElementById("pv_"+pid+"_"+capId);if(!el)return;
  if(c.type==="switch"){el.textContent=value?"On":"Off";var i=el.parentNode.querySelector("input");if(i)i.checked=!!value}
  else if(c.type==="slider"){el.innerHTML=Math.round(value)+'<span class="unit">'+esc(c.min)+"–"+esc(c.max)+"</span>";var rr=el.parentNode.parentNode.querySelector('input[type=range]');if(rr&&document.activeElement!==rr)rr.value=value}
  else if(c.type==="sensor"){el.innerHTML=(typeof value==="number"?(Math.abs(value)<10?value.toFixed(2):value.toFixed(1)):esc(value))+(el.dataset.unit||"")}
  else if(c.type==="color"){if(document.activeElement!==el)el.value=value;var hh=document.getElementById("phx_"+pid+"_"+capId);if(hh)hh.textContent=(""+value).toUpperCase()}
  else if(c.type==="text"){el.textContent=value}
}

/* ---------- log panel ---------- */
var logState={open:false,paused:false,lines:[],unread:0,MAX:200};
function pad2(n){return n<10?"0"+n:""+n}
function logTime(){var d=new Date();return pad2(d.getHours())+":"+pad2(d.getMinutes())+":"+pad2(d.getSeconds())}
function addLog(severity,message){
  var sev=(severity==="warn"||severity==="error")?severity:"info";
  var entry={t:logTime(),s:sev,m:""+(message==null?"":message)};
  logState.lines.push(entry);
  if(logState.lines.length>logState.MAX)logState.lines.shift();
  if(logState.open&&!logState.paused){renderLogLine(entry);trimLogDom()}
  else{logState.unread++;updateLogChip()}
}
function renderLogLine(e){
  var body=$("logBody");
  var empty=body.querySelector(".empty");if(empty)empty.remove();
  var ln=document.createElement("div");ln.className="ln";
  var t=document.createElement("span");t.className="t";t.textContent=e.t;
  var s=document.createElement("span");s.className="s "+e.s;s.textContent=e.s;
  var m=document.createElement("span");m.className="m";m.textContent=e.m;
  ln.appendChild(t);ln.appendChild(s);ln.appendChild(m);
  body.appendChild(ln);
  body.scrollTop=body.scrollHeight;
}
function trimLogDom(){var body=$("logBody"),lns=body.querySelectorAll(".ln");if(lns.length>logState.MAX){var n=lns.length-logState.MAX;for(var i=0;i<n;i++)lns[i].remove()}}
function rerenderLog(){
  var body=$("logBody");body.innerHTML="";
  if(!logState.lines.length){body.innerHTML='<div class="empty">Waiting for log events…</div>';return}
  logState.lines.forEach(renderLogLine);
}
function updateLogChip(){
  var ct=$("logCt");
  if(logState.unread>0&&!logState.open){ct.textContent=logState.unread>99?"99+":(""+logState.unread);ct.classList.add("show")}
  else{ct.classList.remove("show")}
}
function toggleLogPanel(){
  logState.open=!logState.open;
  $("logPanel").classList.toggle("open",logState.open);
  $("logToggle").classList.toggle("active",logState.open);
  $("logToggle").setAttribute("aria-pressed",logState.open?"true":"false");
  if(logState.open){logState.unread=0;updateLogChip();rerenderLog()}
}
$("logToggle").addEventListener("click",toggleLogPanel);
$("logPause").addEventListener("click",function(){
  logState.paused=!logState.paused;
  this.textContent=logState.paused?"Resume":"Pause";
  this.classList.toggle("on",logState.paused);
  if(!logState.paused){logState.unread=0;updateLogChip();rerenderLog()}
});
$("logClear").addEventListener("click",function(){logState.lines=[];logState.unread=0;updateLogChip();rerenderLog()});

/* ---------- OTA overlay ---------- */
var ota={shown:false,failed:false,timer:null};
function otaShow(){
  /* Reset state every call so a fresh OTA after a previous failure starts clean */
  ota.failed=false;
  if(ota.timer){clearTimeout(ota.timer);ota.timer=null}
  var o=$("otaOverlay");o.classList.remove("fail");
  if(!ota.shown){ota.shown=true;o.classList.add("show")}
  $("otaTitle").textContent="Updating firmware";
  $("otaIc").textContent="↑";
  $("otaMsg").textContent="Please keep this page open. Device will reboot when done.";
  $("otaBar").style.width="0%";
  $("otaPct").textContent="starting…";
}
function otaHide(){
  ota.shown=false;ota.failed=false;
  $("otaOverlay").classList.remove("show","fail");
  if(ota.timer){clearTimeout(ota.timer);ota.timer=null}
}
function otaProgress(percent){
  if(percent===-1){
    otaShow();
    ota.failed=true;
    $("otaOverlay").classList.add("fail");
    $("otaIc").textContent="!";
    $("otaTitle").textContent="Update failed";
    $("otaMsg").textContent="Device rejected the update. It is still running the old firmware.";
    $("otaPct").textContent="error";
    return;
  }
  otaShow();
  var p=Math.max(0,Math.min(100,percent|0));
  $("otaBar").style.width=p+"%";
  $("otaPct").textContent=p+"%";
}
function otaDelivered(){
  /* Firmware written to flash — device will reboot momentarily */
  otaShow();
  $("otaBar").style.width="100%";
  $("otaPct").textContent="received";
  $("otaTitle").textContent="Firmware received";
  $("otaMsg").textContent="Update written. Device will reboot now…";
  $("otaIc").textContent="✓";
}
function otaReboot(){
  /* Called when WS closes during an active update — device is rebooting */
  $("otaTitle").textContent="Restarting device";
  $("otaMsg").textContent="The device is rebooting with the new firmware…";
  $("otaPct").textContent="rebooting";
  $("otaBar").style.width="100%";
  if(ota.timer)clearTimeout(ota.timer);
  ota.timer=setTimeout(function(){location.reload()},6000);
}
$("otaDismiss").addEventListener("click",otaHide);
$("otaOverlay").addEventListener("click",function(e){if(e.target===this&&ota.failed)otaHide()});

/* ---------- Add to Home Screen hint + real install prompt ----------
   Two paths converge on the same #pwaHint UI:
   - beforeinstallprompt (Android Chrome, desktop Chrome) → real Install button
     that calls deferredPrompt.prompt(). When this fires, the iOS-style instruction
     text is swapped for the action affordance.
   - No event (iOS Safari) → fall back to platform-specific instruction text via
     maybeShowPwaHint(); Android-without-event also falls into the instruction path.
   The hint is mobile-only by default; beforeinstallprompt is allowed to force it
   on desktop too since Trellis devices on a LAN are commonly visited from a laptop. */
var deferredInstall=null;
function showPwaHint(){
  try{
    if(localStorage.getItem("trellis_pwa_hint_seen")==="1")return;
    if(window.matchMedia&&window.matchMedia("(display-mode: standalone)").matches)return;
    if(window.navigator.standalone)return; /* iOS standalone */
    $("pwaHint").classList.add("show");
  }catch(e){}
}
function maybeShowPwaHint(){
  try{
    if(localStorage.getItem("trellis_pwa_hint_seen")==="1")return;
    if(window.matchMedia&&window.matchMedia("(display-mode: standalone)").matches)return;
    if(window.navigator.standalone)return; /* iOS */
    if(window.innerWidth>=768)return; /* mobile-only fallback path */
    var ua=navigator.userAgent||"";
    var isIOS=/iPad|iPhone|iPod/.test(ua)&&!window.MSStream;
    var isAndroid=/Android/.test(ua);
    if(!isIOS&&!isAndroid)return;
    if(isIOS){$("pwaSub").textContent="Tap Share, then Add to Home Screen"}
    else{$("pwaSub").textContent="Tap menu (⋮), then Add to Home Screen"}
    /* Delay slightly so beforeinstallprompt has a chance to upgrade the text first */
    setTimeout(function(){if(!deferredInstall)$("pwaHint").classList.add("show")},1200);
  }catch(e){}
}
window.addEventListener("beforeinstallprompt",function(e){
  e.preventDefault();
  deferredInstall=e;
  $("pwaSub").textContent="One-tap install";
  $("pwaInstall").classList.add("show");
  showPwaHint();
});
window.addEventListener("appinstalled",function(){
  deferredInstall=null;
  $("pwaHint").classList.remove("show");
  try{localStorage.setItem("trellis_pwa_hint_seen","1")}catch(e){}
});
$("pwaInstall").addEventListener("click",function(){
  if(!deferredInstall)return;
  deferredInstall.prompt();
  deferredInstall.userChoice.then(function(c){
    deferredInstall=null;
    $("pwaHint").classList.remove("show");
    if(c&&c.outcome==="accepted"){try{localStorage.setItem("trellis_pwa_hint_seen","1")}catch(e){}}
  });
});
$("pwaClose").addEventListener("click",function(){
  $("pwaHint").classList.remove("show");
  try{localStorage.setItem("trellis_pwa_hint_seen","1")}catch(e){}
});
/* Register the service worker so the dashboard precaches and survives brief LAN drops.
   The SW file is served from origin root → automatic full-origin scope; no header needed.
   Cache strategy lives in /sw.js. Failures are silent — the page works without a SW. */
if("serviceWorker" in navigator){
  window.addEventListener("load",function(){
    navigator.serviceWorker.register("/sw.js").catch(function(){})
  });
}

/* ---------- scenes + schedules (on-device automation) ----------
   The Scenes section captures the current state of all controllable caps
   (switch / slider / color / text) into a named bundle that can be
   recalled later or fired at a scheduled time. Persisted in NVS by the
   library. Bounded counts come from the GET response so the UI hides the
   capture button when full. */
var scenesState={max:8,maxSetpoints:5,scenes:[]};
var schedState={max:8,schedules:[],dowMask:0x7F};
var DOW_LABELS=["S","M","T","W","T","F","S"];
var DOW_FULL=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
function loadScenes(){
  fetch("/api/scenes").then(function(r){return r.json()}).then(function(d){
    if(!d||!Array.isArray(d.scenes))return;
    scenesState.scenes=d.scenes;
    if(typeof d.max==="number")scenesState.max=d.max;
    if(typeof d.maxSetpoints==="number")scenesState.maxSetpoints=d.maxSetpoints;
    renderScenes();
    renderSchedSceneOptions();
    /* Schedule add-form visibility depends on whether scenes exist, and
       schedule rows show "(deleted scene)" if their scene was removed.
       Re-render the schedule UI from the in-memory list whenever scenes
       change — no network call needed. */
    renderSchedules();
  }).catch(function(){});
}
function loadSchedules(){
  fetch("/api/schedules").then(function(r){return r.json()}).then(function(d){
    if(!d||!Array.isArray(d.schedules))return;
    schedState.schedules=d.schedules;
    if(typeof d.max==="number")schedState.max=d.max;
    renderSchedules();
  }).catch(function(){});
}
function renderScenes(){
  var list=$("scenesList");list.innerHTML="";
  $("scenesCt").textContent=scenesState.scenes.length+" / "+scenesState.max;
  if(!scenesState.scenes.length){
    list.innerHTML='<div class="empty-mini">No scenes yet. Capture the current state to create one.</div>';
  }else{
    scenesState.scenes.forEach(function(s){
      var n=(s.setpoints||[]).length;
      var row=document.createElement("div");row.className="row-card";row.dataset.testid="scene-row-"+s.id;
      row.innerHTML='<div class="lbl"><b></b><span></span></div>'+
        '<div class="acts"><button type="button" class="btn-sm go" data-act="recall">Recall</button>'+
        '<button type="button" class="btn-sm danger" data-act="delete">Delete</button></div>';
      row.querySelector("b").textContent=s.name;
      row.querySelector("span").textContent=n+(n===1?" setpoint":" setpoints");
      row.querySelector('[data-act="recall"]').addEventListener("click",function(){recallScene(s.id,s.name)});
      row.querySelector('[data-act="delete"]').addEventListener("click",function(){deleteScene(s.id,s.name)});
      list.appendChild(row);
    });
  }
  /* hide capture form when at the cap so the user gets a clear "full" signal */
  $("sceneAdd").style.display=scenesState.scenes.length>=scenesState.max?"none":"";
}
function renderSchedules(){
  var list=$("schedList");list.innerHTML="";
  $("schedCt").textContent=schedState.schedules.length+" / "+schedState.max;
  if(!schedState.schedules.length){
    list.innerHTML='<div class="empty-mini">No schedules yet. Pick a scene and a time to fire it automatically.</div>';
  }else{
    schedState.schedules.forEach(function(s){
      var scene=findScene(s.sceneId);
      var name=scene?scene.name:"(deleted scene)";
      var hh=("0"+s.hour).slice(-2),mm=("0"+s.minute).slice(-2);
      var dow=formatDow(s.dow);
      var row=document.createElement("div");row.className="row-card";row.dataset.testid="schedule-row-"+s.id;
      row.innerHTML='<div class="lbl"><b></b><span></span></div>'+
        '<div class="acts"><button type="button" class="btn-sm danger" data-act="delete">Delete</button></div>';
      row.querySelector("b").textContent=name+" — "+hh+":"+mm+" UTC";
      row.querySelector("span").textContent=dow;
      row.querySelector('[data-act="delete"]').addEventListener("click",function(){deleteSchedule(s.id)});
      list.appendChild(row);
    });
  }
  $("schedAdd").style.display=(schedState.schedules.length>=schedState.max||!scenesState.scenes.length)?"none":"";
}
function findScene(id){for(var i=0;i<scenesState.scenes.length;i++){if(scenesState.scenes[i].id===id)return scenesState.scenes[i]}return null}
function formatDow(mask){
  if((mask&0x7F)===0x7F)return"Every day";
  var parts=[];
  for(var i=0;i<7;i++)if(mask&(1<<i))parts.push(DOW_FULL[i]);
  return parts.length?parts.join(", "):"(never)";
}
function renderSchedSceneOptions(){
  var sel=$("schedScene");
  /* preserve current selection if it still exists, otherwise pick first */
  var prev=sel.value;
  sel.innerHTML="";
  scenesState.scenes.forEach(function(s){
    var o=document.createElement("option");o.value=s.id;o.textContent=s.name;sel.appendChild(o);
  });
  if(prev){
    for(var i=0;i<sel.options.length;i++){if(sel.options[i].value===prev){sel.value=prev;break}}
  }
}
function captureScene(){
  var name=($("sceneName").value||"").trim();
  if(!name){toast("Please name the scene first");return}
  fetch("/api/scenes",{method:"POST",headers:{"Content-Type":"application/json"},
    body:JSON.stringify({name:name,capture:true})})
    .then(function(r){return r.json().then(function(d){return{ok:r.ok,d:d}})})
    .then(function(x){
      if(!x.ok){toast(x.d&&x.d.error?x.d.error:"Could not save");return}
      $("sceneName").value="";
      toast('Saved "'+name+'"');
      loadScenes();
    }).catch(function(){toast("Could not save")});
}
function recallScene(id,name){
  fetch("/api/scenes/recall",{method:"POST",headers:{"Content-Type":"application/json"},
    body:JSON.stringify({id:id})})
    .then(function(r){return r.json().then(function(d){return{ok:r.ok,d:d}})})
    .then(function(x){
      if(!x.ok){toast(x.d&&x.d.error?x.d.error:"Recall failed");return}
      toast('Recalled "'+name+'"');
    }).catch(function(){toast("Recall failed")});
}
function deleteScene(id,name){
  if(!confirm('Delete scene "'+name+'"?\n\nAny schedule pointing at it will be removed too.'))return;
  fetch("/api/scenes/delete",{method:"POST",headers:{"Content-Type":"application/json"},
    body:JSON.stringify({id:id})})
    .then(function(r){if(!r.ok)throw 0;return r.json()})
    .then(function(){loadScenes();loadSchedules()})
    .catch(function(){toast("Delete failed")});
}
function buildDowPicker(){
  var c=$("schedDow");c.innerHTML="";
  for(var i=0;i<7;i++){
    var lab=document.createElement("label");
    lab.innerHTML='<input type="checkbox" data-bit="'+i+'" checked><span>'+DOW_LABELS[i]+'</span>';
    lab.classList.add("on");
    var box=lab.querySelector("input");
    box.addEventListener("change",function(e){
      e.target.parentNode.classList.toggle("on",e.target.checked);
    });
    c.appendChild(lab);
  }
}
function readDowMask(){
  var mask=0;
  $("schedDow").querySelectorAll("input").forEach(function(b){if(b.checked)mask|=(1<<parseInt(b.dataset.bit,10))});
  return mask;
}
function addSchedule(){
  if(!scenesState.scenes.length){toast("Create a scene first");return}
  var sceneId=$("schedScene").value;
  if(!sceneId){toast("Pick a scene");return}
  var t=($("schedTime").value||"").split(":");
  if(t.length!==2){toast("Pick a time");return}
  var h=parseInt(t[0],10),m=parseInt(t[1],10);
  if(isNaN(h)||isNaN(m)){toast("Pick a valid time");return}
  var dow=readDowMask();
  if(!dow){toast("Pick at least one day");return}
  fetch("/api/schedules",{method:"POST",headers:{"Content-Type":"application/json"},
    body:JSON.stringify({sceneId:sceneId,hour:h,minute:m,dow:dow})})
    .then(function(r){return r.json().then(function(d){return{ok:r.ok,d:d}})})
    .then(function(x){
      if(!x.ok){toast(x.d&&x.d.error?x.d.error:"Could not add");return}
      toast("Schedule added");
      loadSchedules();
    }).catch(function(){toast("Could not add")});
}
function deleteSchedule(id){
  fetch("/api/schedules/delete",{method:"POST",headers:{"Content-Type":"application/json"},
    body:JSON.stringify({id:id})})
    .then(function(r){if(!r.ok)throw 0;return r.json()})
    .then(function(){loadSchedules()})
    .catch(function(){toast("Delete failed")});
}
$("sceneCapture").addEventListener("click",captureScene);
$("sceneName").addEventListener("keydown",function(e){if(e.key==="Enter")captureScene()});
$("schedAddBtn").addEventListener("click",addSchedule);
buildDowPicker();

loadInfo();
loadPeers();
loadScenes();
loadSchedules();
setInterval(loadPeers,30000);
maybeShowPwaHint();
})();
</script>
</body>
</html>)TWUI";
static const char TRELLIS_WEB_UI_HTML_HASH[] = "c293b76d9c8f8c3f";

#endif
